/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.classandobject;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author Agent
 */
public class DrawGp extends JFrame {

    /**
     * Creates new form DrawGp
     */
    public DrawGp() {
        initComponents();
        setSize(700, 700);
    }
    
    @Override
    public void paint(Graphics g){
        super.setSize(700, 700);
        
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());
        
        
        //head
        g.setColor(Color.red);
        g.fillRoundRect(300, 100, 120, 120, 30, 30);
        
        
        
        g.setColor(Color.decode("#7BF3FF"));
        g.fillRect(350, 110, 20, 20);
        
        //mask
        g.setColor(Color.decode("#FFD700"));
        g.fillRect(310, 120, 100, 80);
        //eye
        g.setColor(Color.WHITE);
        g.fillOval(325, 130, 20, 15);
        g.fillOval(375, 130, 20, 15);
        g.setColor(Color.blue);
        g.fillOval(332, 135, 8, 8);
        g.fillOval(382, 135, 8, 8);
        //mouth
        g.setColor(Color.BLACK);
        g.drawLine(330, 180, 390, 180);
        //body
        g.setColor(Color.red);
        g.fill3DRect(300, 230, 120, 150, true);
        //neck
        g.setColor(Color.red);
        g.fill3DRect(320, 220, 80, 10, false);
        
        //arms
        g.setColor(Color.RED);
        g.fillRect(260, 230, 40, 100);
        g.fillRect(420, 230, 40, 100);
        g.setColor(Color.decode("#FFD700")); 
        g.fillRect(270, 230, 20, 60);
        g.fillRect(430, 230, 20, 60);
        
        //legs
        g.setColor(Color.RED);
        g.fillRect(300, 380, 40, 100);
        g.fillRect(380, 380, 40, 100);
        g.setColor(Color.decode("#FFD700")); 
        g.fillRect(310, 380, 20, 60);
        g.fillRect(390, 380, 20, 60);
        
        //outline
        g.setColor(Color.BLACK);
        g.drawRect(260, 230, 40, 100);
        g.drawRoundRect(300, 100, 120, 120, 30, 30);
        g.draw3DRect(320, 220, 80, 10, false);
        g.draw3DRect(300, 230, 120, 150, true);
        g.drawArc(340, 280, 50, 50, 180, 180);
        
        //body power cell
        int[] xPoints = {330, 355, 380};
        int[] yPoints = {260, 240, 260};
        g.setColor(Color.decode("#28EBFF"));
        g.drawPolyline(xPoints, yPoints, 3);
        g.drawPolygon(xPoints, yPoints, 3);
        g.fillArc(340, 280, 50, 50, 180, 180);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawGp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawGp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawGp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawGp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawGp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
